[supervisord]
nodaemon=true
user=root

[program:vncserver]
command=/bin/bash -c "USER=labuser HOME=/home/labuser vncserver :1 -geometry 1920x1080 -depth 24 && tail -f /home/labuser/.vnc/*.log"
autorestart=true
user=labuser
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
